version: 2
jobs:
  build:
    working_directory: ~/libetrv
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            venv/bin/pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            venv/bin/python3 -m pytest tests --junitxml=test-reports/output.xml
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
